# Build stage: see Dockerfile_rust_builder
ARG RUST_BUILDER=localhost/janitor/rust_builder:latest
FROM ${RUST_BUILDER} AS build

FROM docker.io/debian:testing-slim
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
        ca-certificates \
        devscripts \
        dput \
        gnupg \
        libpython3.14 \
        libssl3 \
        openssh-client \
        python3-breezy \
 && apt-get clean

COPY --from=build /code/target/release/janitor-auto-upload /usr/local/bin/janitor-auto-upload

EXPOSE 9933

ENTRYPOINT ["janitor-auto-upload", "--port=9933", "--listen-address=0.0.0.0"]
