# https://hub.docker.com/_/debian
FROM docker.io/debian:testing-slim AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
        iproute2 \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
       ## Standard packages: ./CONTRIBUTING.md
        ca-certificates \
        cargo \
        g++ \
        gcc \
        libclang-dev \
        libpython3-dev \
        libssl-dev \
        nettle-dev \
        pkg-config \
        protobuf-compiler \
       ## Extra packages
        python3-minimal \
 && apt-get clean

COPY . /code

RUN cargo build --release --manifest-path /code/auto-upload/Cargo.toml --bin janitor-auto-upload

FROM docker.io/debian:testing-slim
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
        ca-certificates \
        devscripts \
        dput \
        gnupg \
        libpython3.14 \
        libssl3 \
        openssh-client \
        python3-breezy \
 && apt-get clean

COPY --from=build /code/target/release/janitor-auto-upload /usr/local/bin/janitor-auto-upload

EXPOSE 9933

ENTRYPOINT ["janitor-auto-upload", "--port=9933", "--listen-address=0.0.0.0"]
