# Build stage: see Dockerfile_rust_builder
ARG RUST_BUILDER=localhost/janitor/rust_builder:latest
FROM ${RUST_BUILDER} AS build

FROM docker.io/debian:testing-slim
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
        ca-certificates \
        git \
        libpython3.14 \
        libssl3 \
        python3-breezy \
 && apt-get clean

COPY --from=build /code/target/release/janitor-git-store /usr/local/bin/janitor-git-store

VOLUME /git

EXPOSE 9923

EXPOSE 9924

ENTRYPOINT ["janitor-git-store", "--port=9923", "--public-port=9924", "--listen-address=0.0.0.0"]
