# Build stage: see Dockerfile_rust_builder
ARG RUST_BUILDER=localhost/janitor/rust_builder:latest
FROM ${RUST_BUILDER} AS build

FROM docker.io/debian:testing-slim
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
        ca-certificates \
        libssl3 \
        openssh-client \
        python3-breezy \
 && apt-get satisfy --yes --no-install-recommends \
        "libpython$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])')" \
 && apt-get clean

COPY --from=build /code/target/release/janitor-publish /usr/local/bin/janitor-publish
COPY --from=build /code/target/release/janitor-publish-one /usr/local/bin/janitor-publish-one

EXPOSE 9912

ENTRYPOINT ["janitor-publish", "--port=9912", "--listen-address=0.0.0.0"]
