# https://hub.docker.com/_/debian
FROM docker.io/debian:testing-slim AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
        iproute2 \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
       ## Standard packages: ./CONTRIBUTING.md
        ca-certificates \
        cargo \
        g++ \
        gcc \
        libclang-dev \
        libpython3-dev \
        libssl-dev \
        nettle-dev \
        pkg-config \
        protobuf-compiler \
       ## Extra packages
        python3-minimal \
 && apt-get clean

COPY . /code

RUN cargo build --release --manifest-path /code/bzr-store/Cargo.toml --bin janitor-bzr-store

FROM docker.io/debian:testing-slim
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
        brz \
        ca-certificates \
        libpython3.14 \
        libssl3 \
        python3-breezy \
 && apt-get clean

COPY --from=build /code/target/release/janitor-bzr-store /usr/local/bin/janitor-bzr-store

VOLUME /bzr

EXPOSE 9929

EXPOSE 9930

ENTRYPOINT ["janitor-bzr-store", "--port=9929", "--public-port=9930", "--listen-address=0.0.0.0"]
