# Build stage: see Dockerfile_rust_builder
ARG RUST_BUILDER=localhost/janitor/rust_builder:latest
FROM ${RUST_BUILDER} AS build

FROM docker.io/debian:testing-slim
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
        brz \
        ca-certificates \
        libpython3.14 \
        libssl3 \
        python3-breezy \
 && apt-get clean

COPY --from=build /code/target/release/janitor-bzr-store /usr/local/bin/janitor-bzr-store

VOLUME /bzr

EXPOSE 9929

EXPOSE 9930

ENTRYPOINT ["janitor-bzr-store", "--port=9929", "--public-port=9930", "--listen-address=0.0.0.0"]
